import * as Lucide from 'lucide-react';

const importsToCheck = [
    "ArrowRight", "CheckCircle", "ShieldCheck", "Users", "Building2",
    "Clock", "Calendar", "CreditCard", "BarChart", "MapPin",
    "FileText", "Globe", "Lock", "Zap", "Star", "TrendingUp",
    "ChevronRight", "Sparkles", "Award", "Target", "Users2",
    "Briefcase", "PieChart", "LineChart", "Shield", "Database",
    "Smartphone", "Laptop", "Tablet", "Headphones", "MessageSquare",
    "Download", "Play", "ExternalLink", "Bell", "Settings",
    "Folder", "Search", "Filter", "Edit", "Trash2",
    "Share2", "Printer", "Maximize2", "RefreshCw", "Save",
    "AlertCircle", "Info", "HelpCircle", "BookOpen", "Video",
    "Image", "File", "FolderOpen", "Archive", "Inbox",
    "Send", "Hash", "AtSign", "Key", "Eye", "EyeOff",
    "Upload", "Cloud", "Server", "Cpu", "HardDrive",
    "Wifi", "Battery", "Signal", "Radio", "Satellite",
    "Tool", "Wrench", "Hammer", "Package", "Truck",
    "Store", "ShoppingCart", "Tag", "Percent", "DollarSign",
    "Receipt", "Calculator", "Bank", "Wallet", "Coins",
    "Bitcoin", "ShoppingBag",
    "Gift", "Box", "Layers",
    "Grid", "List", "Columns", "Layout", "Type",
    "Bold", "Italic", "Underline", "AlignLeft", "AlignCenter",
    "AlignRight", "ListOrdered",
    "CheckSquare", "Square", "Circle",
    "ToggleLeft", "ToggleRight", "Slider", "BarChart2",
    "TrendingDown",
    "Watch", "Timer", "Hourglass", "Map", "Navigation",
    "Compass", "Flag", "Trophy",
    "Crown", "Medal", "Heart", "ThumbsUp", "Smile",
    "Frown", "Meh", "MessageCircle", "Phone", "PhoneCall",
    "Mail", "Megaphone", "Rss", "Share",
    "Camera",
    "Mic", "Volume2",
    "Music", "Film", "Tv", "Monitor",
    "Mouse", "Keyboard",
    "Bluetooth",
    "Thermometer", "Droplets", "Wind", "Sun", "Moon",
    "CloudRain", "CloudSnow",
    "CloudLightning", "Umbrella", "Waves", "Tree",
    "Flower", "Leaf", "Sprout", "Coffee", "Wine",
    "Utensils", "Home", "Building", "Factory", "Warehouse",
    "Navigation2",
    "Crosshair",
    "ShieldOff", "Fingerprint", "User",
    "UserCheck", "UserPlus", "UserMinus", "UserX",
    "UserCog", "Cog",
    "BellOff", "VolumeX", "MicOff", "VideoOff",
    "CameraOff",
    "Receive"
];

const missing = importsToCheck.filter(name => !Lucide[name]);
console.log("Missing icons:", missing);
